/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled 2"
  https://create.arduino.cc/cloud/things/3ad52307-331a-4015-876f-5c80e0c88120 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  String ifttt;
  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#include <BH1750FVI.h>
BH1750FVI LightSensor(BH1750FVI::k_DevModeContLowRes);

float luminous; 
float expose;

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
  LightSensor.begin();

}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  expose = LightSensor.Getluminous();
  Serial.println(expose);
  
  if(expose > 200)
  {
     ifttt = "light is being sensed";
  }
  
  else if(expose <= 200)
  {
    ifttt = "no light is being sensed";
    Serial.println("light");
  }
  delay(400);
  
}

/*
  Since Message is READ_WRITE variable, onMessageChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onMessageChange()  {
  // Add your code here to act upon Message change
}
/*
  Since Light3 is READ_WRITE variable, onLight3Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onLight3Change()  {
  // Add your code here to act upon Light3 change
}
